server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    # host: 127.0.0.1
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: local
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/git_local_repo
        git:
          uri: file:///C:/Users/amorf/git_local_repo
          # On Windows, you need an extra "/" in the file URL if it is absolute with a drive prefix (for example,file:///${user.home}/config-repo). 공식문서 참고
          default-label: master

          #uri: [깃허브 url] public
          #username:[아이디] private
          #password:[비밀번호] private
management:
  endpoints:
    web:
      exposure:
        # include: health, busrefresh
        include: health, busrefresh, refresh, metrics
encrypt:
  #key: rnjsthfdlgkdlqkdl12345
  key-store:
    location: file:///${user.home}/keystore/apiEncryptionKey.jks
    password: 123456
    alias: apiEncryptionKey


